services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urlshortenerdb
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d urlshortenerdb"]
      interval: 2s
      timeout: 5s
      retries: 10

  url-shortener-service:
    image: url-shortener-service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy