openapi: 3.0.0
info:
  title: URL Shortener API
  description: API for URL shortening service
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /api/url-shortener/v1/health:
    get:
      summary: Health check
      description: Check the health status of the service
      tags:
        - health
      responses:
        "200":
          description: Service is healthy
  /api/url-shortener/v1/shorten:
    post:
      summary: Create a shortened URL
      description: Creates a consistent shortened URL for the given URL
      tags:
        - short URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateShortenURLRequest"
      responses:
        "201":
          description: URL shortened successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateShortenURLResponse"
        "400":
          description: The body is malformated or missing information
        "422":
          description: The original URL is invalid
        "500":
          description: Unexpected error
  /{slug}:
    get:
      summary: Retrieve an original URL
      description: Retrieves an original non malicious URL given a slug
      tags:
        - short URL
      parameters:
        - name: slug
          in: path
          required: true
          description: The slug for the shortened URL
          schema:
            type: string
            example: abc12345
        - name: redirect
          in: query
          required: false
          description: If set to 'true', redirects to the original URL instead of returning it
          schema:
            type: string
            enum:
              - "true"
            default: "false"
      responses:
        "200":
          description: Original URL retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOriginalURLResponse"
        "302":
          description: Original URL retrieved and redirecting to it as asked
        "403":
          description: A malware has been detected on the URL, if you really want to access the URL, use /force API
        "404":
          description: No URL associated to the given slug found
        "422":
          description: The slug is invalid
        "500":
          description: Unexpected error
  /{slug}/force:
    get:
      summary: Force to retrieve an original URL
      description: Force the retrieval of an original URL (even if malicious) given a slug
      tags:
        - short URL
      parameters:
        - name: slug
          in: path
          required: true
          description: The slug for the shortened URL
          schema:
            type: string
            example: abc12345
        - name: redirect
          in: query
          required: false
          description: If set to 'true', redirects to the original URL instead of returning it
          schema:
            type: string
            enum:
              - "true"
            default: "false"
      responses:
        "200":
          description: Original URL retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOriginalURLResponse"
        "302":
          description: Original URL retrieved and redirecting to it as asked
        "404":
          description: No URL associated to the given slug found
        "422":
          description: The slug is invalid
        "500":
          description: Unexpected error
  /api/url-shortener/v1/statistics:
    get:
      summary: Retrieve statistics for a given URL
      description: Retrieves both accessed counter and shortened counter statistics for a given URL
      tags:
        - statistics
      parameters:
        - name: encoded_url
          in: query
          required: true
          description: A HTTP encoded URL
          schema:
            type: string
            example: "https%3A%2F%2Fexample.com"
      responses:
        "200":
          description: Statistics retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetStatisticsForURLResponse"
        "400":
          description: Missing URL or URL not HTTP encoded
        "500":
          description: Unexpected error
  /api/url-shortener/v1/statistics/accessed:
    get:
      summary: Retrieve top accessed statistics
      description: Retrieves top URLs with the highest accessed counter statistics
      tags:
        - statistics
      parameters:
        - name: limit
          in: query
          required: false
          description: The limit of result to retrieve (max 1 000)
          schema:
            type: integer
            example: 10
      responses:
        "200":
          description: Top statistics retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetTopStatisticsAccessedResponse"
        "400":
          description: Invalid query parameter
        "500":
          description: Unexpected error
  /api/url-shortener/v1/statistics/shortened:
    get:
      summary: Retrieve top shortened statistics
      description: Retrieves top URLs with the highest shortened counter statistics
      tags:
        - statistics
      parameters:
        - name: limit
          in: query
          required: false
          description: The limit of result to retrieve (max 1 000)
          schema:
            type: integer
            example: 10
      responses:
        "200":
          description: Top statistics retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetTopStatisticsShortenedResponse"
        "400":
          description: Invalid query parameter
        "500":
          description: Unexpected error

components:
  schemas:
    CreateShortenURLRequest:
      type: object
      required:
        - original_url
      properties:
        original_url:
          type: string
          example: "https://example.com"

    CreateShortenURLResponse:
      type: object
      properties:
        short_url:
          type: string
          example: "http://localhost:8080/abc12345"

    GetOriginalURLResponse:
      type: object
      properties:
        original_url:
          type: string
          example: "https://example.com"

    GetStatisticsForURLResponse:
      type: object
      properties:
        url:
          type: string
          example: "https://example.com"
        shortened_counter:
          type: integer
          example: 10
        accessed_counter:
          type: integer
          example: 5

    GetTopStatisticsAccessedResponse:
      type: object
      properties:
        urls:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                example: "https://example.com"
              accessed_counter:
                type: integer
                example: 10

    GetTopStatisticsShortenedResponse:
      type: object
      properties:
        urls:
          type: array
          items:
            type: object
            properties:
              url:
                type: string
                example: "https://example.com"
              shortened_counter:
                type: integer
                example: 10
